name: 'fish-shop/install-plugin'
description: 'A GitHub action for installing fish shell plugins'
branding:
  icon: 'arrow-down'
  color: 'green'
inputs:
  plugin-manager:
    description: 'The name of the fish shell plugin manager to use'
    required: true
  plugins:
    description: 'The plugin(s) to install; this value is passed verbatim as an argument to the install command of the chosen plugin manager and the values supported may differ between tools'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: fish-shop/install-plugin-manager@08d167ca0ac58568bb5806324b308256b7d077ef # v2.2.11
      with:
        plugin-manager: ${{ inputs.plugin-manager }}
    - name: Install plugins
      run: |
        set -gx TERM xterm-256color
        switch ${{ inputs.plugin-manager }}
            case 'fisher'
                fisher install ${{ inputs.plugins }}
            case 'oh-my-fish'
                omf install ${{ inputs.plugins }}
        end
      shell: fish {0}
