name: 'fish-shop/install-plugin'
description: 'A GitHub action for installing fish shell plugins'
branding:
  icon: 'arrow-down'
  color: 'green'
inputs:
  plugin-manager:
    description: 'The name of the fish shell plugin manager to use'
    required: true
  plugins:
    description: 'The plugin(s) to install; this value is passed verbatim as an argument to the install command of the chosen plugin manager and the values supported may differ between tools'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: fish-shop/install-plugin-manager@787dd6e02298ef6256f4e30d55d93008d921fcd4 # v2.3.6
      with:
        plugin-manager: ${{ inputs.plugin-manager }}
    - name: Install plugins
      env:
        PLUGIN_MANAGER: ${{ inputs.plugin-manager }}
        PLUGINS: ${{ inputs.plugins }}
      run: |
        set -gx TERM xterm-256color

        set plugin_manager (string escape --no-quoted -- $PLUGIN_MANAGER)
        set plugins (string split --no-empty ' ' -- $PLUGINS | string escape --no-quoted)

        switch $plugin_manager
            case 'fisher'
                fisher install $plugins
            case 'oh-my-fish'
                omf install $plugins
            case '*'
                echo "Unrecognised plugin manager: '$plugin_manager'" >&2; and exit 1
        end
      shell: fish {0}
