name: Dependency Review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@ac154a774b835fd87b181c3b9bbed9fad946ad39 # v1.14.17
