name: Dependency Review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@9ce460dc45b24d21ba41ea70166c791cfb3c26c8 # v1.14.21
