name: Gitleaks SAST scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  gitleaks:
    name: Gitleaks SAST scan
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/gitleaks.yml@63d32facd513f5dbe37f24338592c6895300450e # v1.14.14
    secrets:
      gitleaks_license: ${secrets.GITLEAKS_LICENSE}
