name: Gitleaks SAST scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  gitleaks:
    name: Gitleaks SAST scan
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/gitleaks.yml@b05520ac668ee5e7c7b11b1b9edc3261282e7c72 # v1.14.15
    secrets:
      gitleaks_license: ${secrets.GITLEAKS_LICENSE}
