name: Markdown Links Check
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  markdown-links:
    name: Markdown Links Check
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@b05520ac668ee5e7c7b11b1b9edc3261282e7c72 # v1.14.15
