name: Markdown Links Check
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  markdown-links:
    name: Markdown Links Check
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@ac154a774b835fd87b181c3b9bbed9fad946ad39 # v1.14.17
