name: OpenSSF Scorecard Analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '0 3 * * 1'
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  analysis:
    name: OpenSSF Scorecard Analysis
    permissions:
      security-events: write # Needed to upload the results to code scanning dashboard
      id-token: write # Needed to publish results to OpenSSF API and get a badge
    uses: fish-shop/workflows/.github/workflows/openssf-scorecard.yml@109613a6626e35f9f5fb69d7f530744cad7bed86 # v1.14.22
