name: Release Tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    name: Release Tags
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@9ce460dc45b24d21ba41ea70166c791cfb3c26c8 # v1.14.21
