name: Release Tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    name: Release Tags
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@b05520ac668ee5e7c7b11b1b9edc3261282e7c72 # v1.14.15
