name: Release Tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    name: Release Tags
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@109613a6626e35f9f5fb69d7f530744cad7bed86 # v1.14.22
