name: Action Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron: '30 19 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  tests:
    name: Action Tests
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - ubuntu-22.04
          - ubuntu-24.04
        plugin-manager:
          - fisher
          - oh-my-fish
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@e83b4f8c7c4d80c3b65ee0eb5d0e3bf4816536ee # v2.1.21
      - if: matrix.plugin-manager != 'oh-my-fish'
        name: Install plugin using <username>/<repo> name
        uses: ./
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: marcransome/pond
      - if: matrix.plugin-manager == 'oh-my-fish'
        name: Install plugin using GitHub URL
        uses: ./
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: https://github.com/marcransome/pond
      - name: Check plugin installed
        run: type -q pond
        shell: fish {0}
